# Generated by Django 4.1.7 on 2023-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChargeSessionCost', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesessioncost',
            name='charge_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
